### ISSUE TITLE
Apollo-Soyuz

### ISSUE THREAD

**Issue by russss** [Spacelog/Spacelog#148]
ASTP transcripts have been newly released here:
http://www.archive.org/details/Apollo-soyuzTestProgram

After A11 and possibly A8, we should work on getting ASTP done as soon as possible. It's newly-released, it's politically interesting, and it involves Tom Stafford. What more do you want?

**Comment by georgebrock** [comment]
Moving this to a Trello card on the missions board, and closing: https://trello.com/c/cj1j7YUL
