### ISSUE TITLE
Land Apollo 8

### ISSUE THREAD

**Issue by SteveMarshall** [Spacelog/Spacelog#155]
The transcripts have been done by  Jeremy Weatherford and Greg Roodt , so we're into the cycle of images & _meta. Because this is Apollo, we need orbital and suchlike, so we need:

- biographies plus photos & avatars
- phases & phase images
- additional (inline) images
- key moments
- homepage quotes
- mission summary
- orbital diagrams

… What else?

**Comment by georgebrock** [comment]
I'm working my way through this at the moment.

See https://trello.com/c/riemIKxT for details.

**Comment by georgebrock** [comment]
There's a PR open for all of the transcript and _meta stuff (#219).

**Comment by georgebrock** [comment]
Closing, since this is all documented on the missions Trello board.
