### ISSUE TITLE
Gemini III: MEDIA transcript

### ISSUE THREAD

**Issue by georgebrock** [Spacelog/Spacelog#162]
Lots of good photos here:  http://science.ksc.nasa.gov/mirrors/images/html/gt3.htm
Some audio (which we don't support yet, but…) here: http://crotrak.com/gemini.htm

**Comment by jaylett** [comment]
Another possible launch photo: http://spaceflight.nasa.gov/gallery/images/gemini/gemini3/html/s65-20742.html

**Comment by georgebrock** [comment]
Moving this information to the mission Trello card, since it's content and not code: https://trello.com/c/fyI8rWZH
