### ISSUE TITLE
Mercury 4: PNGs of original transcripts

### ISSUE THREAD

**Issue by georgebrock** [Spacelog/Spacelog#203]

**Comment by georgebrock** [comment]
For Apollo 8, I found this little bash script did the trick:

```bash
for i in {0..755}; do
  echo "Page $(expr $i + 1) / 756"
  convert -density 150 "AS08_TEC.PDF[$i]" "$(expr $i + 1).png"
done
```

**Comment by jaylett** [comment]
That's useful — I suspect it's faster than what I do for Kallisto, which is more like:

    convert -density 150 <pdf-file> png/page-%03d.png

**Comment by georgebrock** [comment]
I don't know if it's faster, but the feedback during the run definitely gave me more confidence that it was working.

**Comment by georgebrock** [comment]
Oh, wait, @SteveMarshall solved this 5 years ago: https://github.com/Spacelog/Spacelog/blob/master/tools/pdf_to_images.py

**Comment by georgebrock** [comment]
Closing in favour of #224
