### ISSUE TITLE
Django upgrade broke error pages and JSON responses

### ISSUE THREAD

**Issue by georgebrock** [Spacelog/Spacelog#218]
In `ErrorView` and `JsonTemplateView`, we override or call `TemplateView.get_response` to modify the properties of the response in some way.

Unfortunately, this method no longer exists: https://github.com/django/django/commit/e0dcd7666aec15a2348bef346b4ce683ddf376b3

**Comment by georgebrock** [comment]
Django upgrade happend here: https://github.com/Spacelog/Spacelog/commit/7970ef004838d3c5b8db168e8ee66ff29edf71b1

**Comment by jaylett** [comment]
We should probably upgrade at least to 1.4 while we're looking at this. (Which is LTS until September IIRC.) Given we don't use the ORM, upgrading to 1.8 shouldn't be hugely painful either. 1.7 at least has `self.content_type` which would probably be an easier way of doing what we're doing in `JsonTemplateView`. (Also `request.is_ajax()`.)

`ErrorView` can be easily reworked to pass `status=self.error_code` into `render_to_response()` as well, I think.

**Comment by georgebrock** [comment]
Closing this issue, now there's a PR for it.
