### ISSUE TITLE
Quotation marks on press page replaced by strange characters

### ISSUE THREAD

**Issue by alicetragedy** [Spacelog/Spacelog#233]
I came across the website (love the project!) and noticed a strange thing on the press page: the quotation marks are replaced by a `â`. I've attached a screenshot (you can see the characters as well as part of my web inspector) below and I believe it might have to do with [this bit in the css](https://github.com/Spacelog/Spacelog/blob/master/website/static/css/screen/homepage.scss#L68), however I didn't run it locally so I haven't been able to double-check if simply removing those few declarations fixes the problem. Would be happy to help further! 

<img width="1199" alt="screen shot 2016-02-05 at 22 14 56" src="https://cloud.githubusercontent.com/assets/3143348/12859422/5d0622e8-cc56-11e5-9012-6b1aec30b52e.png">

**Comment by jaylett** [comment]
Thanks for reporting this — I believe the problem is a character set issue while building the CSS. @georgebrock may know more. I agree in the short term we should remove the quotation marks as you suggest, while we figure out how to make them work properly again.

**Comment by alicetragedy** [comment]
:+1: 
feel free to ping me if you need me to test anything or want some help :)

**Comment by JPinSPACE** [comment]
I was going to make a new issue for this but I bet it's related. Check out the `â|` symbols by the CAPCOM on this page: http://apollo13.spacelog.org/04:06:11:57/#log-line-367917

**Comment by jaylett** [comment]
@JPinSPACE it looks like the same problem to me (getting the encoding wrong when we generate the CSS file). Thanks for noting that!

**Comment by georgebrock** [comment]
We think switching from the Ruby implementation of Sass to the Python bindings for libsass will help.

This worked locally for @jaylett, but is missing development mode live updating: https://gist.github.com/jaylett/b7a5fea55d065fa96afa

**Comment by norm** [comment]
I've previously used https://gist.github.com/norm/271bf72f77ae9df0fd9e — "Minimum Viable Python-only automatic SASS compilation"

**Comment by jaylett** [comment]
#238 hasn't been deployed yet, so this is still an open issue.

**Comment by georgebrock** [comment]
We've switched over to a new server, and fixed this in the process.
