### ISSUE TITLE
Missing image on "get involved" page

### ISSUE THREAD

**Issue by JPinSPACE** [Spacelog/Spacelog#237]
It's looking for an image with the page `http://spacelog.org/assets/img/transcripts-pile.png` and not finding it.

Get involved page: http://spacelog.org/get-involved/

**Comment by georgebrock** [comment]
Good catch! I'm pretty sure this is fixed by #232, so when we merge that PR it should be resolved.

**Comment by georgebrock** [comment]
This fix was deployed a while ago when we switched over to the new server.
