### ISSUE TITLE
Dynamic contributors list on the global about page

### ISSUE THREAD

**Issue by georgebrock** [Spacelog/Spacelog#240]
When people help to clean missions we add them to the mission's `_meta` transcript (Kallisto builds this list for us when the mission's been cleaned there). We also add people to the global site's about page, but we've been somewhat inconsistent about doing that.

Instead of updating the global site by hand every time, let's just pull in the list from Redis.

**Comment by jaylett** [comment]
Alternatively we could keep the global site to development work, and note there that individual cleaners are notes on the mission about pages. I'd prefer listing everyone for now, but am aware that list might become huge :-)
